spring.application.name=autoport

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d7s21hkm0tmc738l7iag-a.singapore-postgres.render.com/autoport_db_q8rl
spring.datasource.username=autoport_db_q8rl_user
spring.datasource.password=rAMlzSklSKZl9msIBU1WjuWC4RP7MsQI
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation123456789012345678901234567890
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:your-email@gmail.com}
spring.mail.password=${MAIL_PASSWORD:your-app-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=${MAIL_USERNAME:your-email@gmail.com}
spring.mail.properties.mail.smtp.starttls.required=true